language: ruby
bundler_args: --without debug
script: "bundle exec rspec spec"
sudo: false
cache: bundler
rvm:
 - 2.2.4
 - 2.3.0
 - jruby-9.0.4.0
 - rbx-2
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
jdk: oraclejdk8
matrix:
  allow_failures:
      - rvm: jruby-9.0.4.0
      - rvm: rbx-2
